import { ProjectId } from '~/models/project-id.enum';

export const PROJECTS_NAV = {
  [ProjectId.Home]: {
    groups: [
      {
        title: 'Home',
        icon: 'mdi-view-dashboard',
        items: [
          { title: 'Home', path: '/' },
          { title: 'Angular Quick Forms', path: '/angular-quick-forms' },
          { title: 'Ionic Selectable', path: '/ionic-selectable' },
        ],
      },
    ],
  },
  [ProjectId.AngularQuickForms]: {
    groups: [
      {
        title: 'Introduction',
        icon: 'mdi-script-text-outline',
        items: [{ title: 'Introduction', path: '/angular-quick-forms' }],
      },
    ],
  },
  [ProjectId.IonicSelectable]: {
    mainItem: {
      title: 'Ionic Selectable',
      subtitle: 'An Ionic Component',
      icon: 'https://avatars.githubusercontent.com/u/61024758?v=4',
    },
    groups: [
      {
        title: 'Introduction',
        icon: 'mdi-script-text-outline',
        items: [
          { title: 'About', path: '/ionic-selectable' },
          { title: 'Getting started', path: '/ionic-selectable/getting-started' },
          { title: 'Frequently asked questions', path: '/ionic-selectable/frequently-asked-questions' },
          { title: 'Errors', path: '/ionic-selectable/errors' },
          { title: 'Contributing', path: '/ionic-selectable/contributing' },
        ],
      },
      {
        title: 'Theming',
        icon: 'mdi-palette-outline',
        items: [{ title: 'CSS classes', path: '/ionic-selectable/css-classes' }],
      },
      {
        title: 'Use cases',
        icon: 'mdi-text-box-search-outline',
        items: [
          { title: 'Basic usage', path: '/ionic-selectable/basic-usage' },
          { title: 'Cascading selection', path: '/ionic-selectable/cascading-selection' },
          { title: 'Customizing footer buttons', path: '/ionic-selectable/customizing-footer-buttons' },
          { title: 'Disabling items', path: '/ionic-selectable/disabling-items' },
          { title: 'Firebase', path: '/ionic-selectable/firebase' },
          { title: 'Inside modal', path: '/ionic-selectable/inside-modal' },
          { title: 'Initial value', path: '/ionic-selectable/initial-value' },
          { title: 'Infinite scroll', path: '/ionic-selectable/infinite-scroll' },
          {
            title: 'Infinite scroll with multiple values',
            path: '/ionic-selectable/infinite-scroll-multiple-values',
          },
          { title: 'Ionic labels', path: '/ionic-selectable/ionic-labels' },
          { title: 'Primitive types', path: '/ionic-selectable/primitive-types' },
          { title: 'Search items asynchronously', path: '/ionic-selectable/search-items-asynchronously' },
          { title: 'Search by several item fields', path: '/ionic-selectable/search-by-several-item-fields' },
          { title: 'Virtual scroll', path: '/ionic-selectable/virtual-scroll' },
        ],
      },
      {
        title: 'Grouping',
        icon: 'mdi-file-tree',
        items: [
          { title: 'Grouping items', path: '/ionic-selectable/grouping-items' },
          {
            title: 'Grouping items with virtual scroll',
            path: '/ionic-selectable/grouping-items-virtual-scroll',
          },
        ],
      },
      {
        title: 'Editing',
        icon: 'mdi-square-edit-outline',
        items: [
          {
            title: 'Adding, editing and deleting items',
            path: '/ionic-selectable/editing-adding-editing-and-deleting-items',
          },
          {
            title: 'Adding, editing and deleting items asynchronously',
            path: '/ionic-selectable/editing-adding-editing-and-deleting-items-asynchronously',
          },
          {
            title: 'Adding item when search fails',
            path: '/ionic-selectable/editing-adding-item-when-search-fails',
          },
          {
            title: 'Adding item asynchronously when search fails',
            path: '/ionic-selectable/editing-adding-item-asynchronously-when-search-fails',
          },
        ],
      },
      {
        title: 'Templates',
        icon: 'mdi-xml',
        items: [
          { title: 'Add item template', path: '/ionic-selectable/add-item-template' },
          { title: 'Close button template', path: '/ionic-selectable/close-button-template' },
          { title: 'Footer template', path: '/ionic-selectable/footer-template' },
          { title: 'Group template', path: '/ionic-selectable/group-template' },
          { title: 'Group end template', path: '/ionic-selectable/group-end-template' },
          { title: 'Header template', path: '/ionic-selectable/header-template' },
          { title: 'Icon template', path: '/ionic-selectable/icon-template' },
          { title: 'Item template', path: '/ionic-selectable/item-template' },
          { title: 'Item end template', path: '/ionic-selectable/item-end-template' },
          { title: 'Item icon template', path: '/ionic-selectable/item-icon-template' },
          { title: 'Message template', path: '/ionic-selectable/message-template' },
          { title: 'Multiple values template', path: '/ionic-selectable/multiple-values-template' },
          {
            title: 'Multiple values with ellipsis template',
            path: '/ionic-selectable/multiple-values-ellipsis-template',
          },
          { title: 'Placeholder template', path: '/ionic-selectable/placeholder-template' },
          { title: 'Search fail template', path: '/ionic-selectable/search-fail-template' },
          { title: 'Title template', path: '/ionic-selectable/title-template' },
          { title: 'Value template', path: '/ionic-selectable/value-template' },
        ],
      },
      {
        title: 'Forms',
        icon: 'mdi-form-select',
        items: [
          { title: 'FormArray', path: '/ionic-selectable/form-array' },
          { title: 'FormControl', path: '/ionic-selectable/form-control' },
          { title: 'Min/max selection', path: '/ionic-selectable/min-max-selection' },
        ],
      },
      {
        title: 'Fields',
        icon: 'mdi-cube-outline',
        items: [
          { title: 'addButtonText', path: '/ionic-selectable/add-button-text-field' },
          { title: 'canAddItem', path: '/ionic-selectable/can-add-item-field' },
          { title: 'canClear', path: '/ionic-selectable/can-clear-field' },
          { title: 'canDeleteItem', path: '/ionic-selectable/can-delete-item-field' },
          { title: 'canSaveItem', path: '/ionic-selectable/can-save-item-field' },
          { title: 'canSearch', path: '/ionic-selectable/can-search-field' },
          { title: 'clearButtonText', path: '/ionic-selectable/clear-button-text-field' },
          { title: 'closeButtonText', path: '/ionic-selectable/close-button-text-field' },
          { title: 'closeButtonSlot', path: '/ionic-selectable/close-button-slot-field' },
          { title: 'confirmButtonText', path: '/ionic-selectable/confirm-button-text-field' },
          { title: 'disabledItems', path: '/ionic-selectable/disabled-items-field' },
          { title: 'groupColor', path: '/ionic-selectable/group-color-field' },
          { title: 'groupValueField', path: '/ionic-selectable/group-value-field-field' },
          { title: 'groupTextField', path: '/ionic-selectable/group-text-field-field' },
          { title: 'hasInfiniteScroll', path: '/ionic-selectable/has-infinite-scroll-field' },
          { title: 'hasConfirmButton', path: '/ionic-selectable/has-confirm-button-field' },
          { title: 'hasSearchText', path: '/ionic-selectable/has-search-text-field' },
          { title: 'hasVirtualScroll', path: '/ionic-selectable/has-virtual-scroll-field' },
          { title: 'headerColor', path: '/ionic-selectable/header-color-field' },
          { title: 'itemIconSlot', path: '/ionic-selectable/item-icon-slot-field' },
          { title: 'items', path: '/ionic-selectable/items-field' },
          { title: 'itemsToConfirm', path: '/ionic-selectable/items-to-confirm-field' },
          { title: 'isEnabled', path: '/ionic-selectable/is-enabled-field' },
          { title: 'isMultiple', path: '/ionic-selectable/is-multiple-field' },
          { title: 'isConfirmButtonEnabled', path: '/ionic-selectable/is-confirm-button-enabled-field' },
          { title: 'isOnSearchEnabled', path: '/ionic-selectable/is-on-search-enabled-field' },
          { title: 'isOpened', path: '/ionic-selectable/is-opened-field' },
          { title: 'isSearching', path: '/ionic-selectable/is-searching-field' },
          { title: 'itemValueField', path: '/ionic-selectable/item-value-field-field' },
          { title: 'itemTextField', path: '/ionic-selectable/item-text-field-field' },
          { title: 'label', path: '/ionic-selectable/label-field' },
          { title: 'modalCssClass', path: '/ionic-selectable/modal-css-class-field' },
          { title: 'modalEnterAnimation', path: '/ionic-selectable/modal-enter-animation-field' },
          { title: 'modalLeaveAnimation', path: '/ionic-selectable/modal-leave-animation-field' },
          { title: 'placeholder', path: '/ionic-selectable/placeholder-field' },
          { title: 'searchDebounce', path: '/ionic-selectable/search-debounce-field' },
          { title: 'searchFailText', path: '/ionic-selectable/search-fail-text-field' },
          { title: 'searchPlaceholder', path: '/ionic-selectable/search-placeholder-field' },
          { title: 'searchText', path: '/ionic-selectable/search-text-field' },
          { title: 'shouldBackdropClose', path: '/ionic-selectable/should-backdrop-close-field' },
          { title: 'shouldFocusSearchbar', path: '/ionic-selectable/should-focus-searchbar-field' },
          { title: 'shouldStoreItemValue', path: '/ionic-selectable/should-store-item-value-field' },
          {
            title: 'virtualScrollApproxItemHeight',
            path: '/ionic-selectable/virtual-scroll-approx-item-height-field',
          },
          { title: 'virtualScrollHeaderFn', path: '/ionic-selectable/virtual-scroll-header-fn-field' },
        ],
      },
      {
        title: 'Methods',
        icon: 'mdi-code-parentheses',
        items: [
          { title: 'addItem()', path: '/ionic-selectable/add-item-method' },
          { title: 'clear()', path: '/ionic-selectable/clear-method' },
          { title: 'close()', path: '/ionic-selectable/close-method' },
          { title: 'confirm()', path: '/ionic-selectable/confirm-method' },
          { title: 'deleteItem()', path: '/ionic-selectable/delete-item-method' },
          { title: 'disableInfiniteScroll()', path: '/ionic-selectable/disable-infinite-scroll-method' },
          { title: 'enableInfiniteScroll()', path: '/ionic-selectable/enable-infinite-scroll-method' },
          { title: 'endInfiniteScroll()', path: '/ionic-selectable/end-infinite-scroll-method' },
          { title: 'endSearch()', path: '/ionic-selectable/end-search-method' },
          { title: 'hasValue()', path: '/ionic-selectable/has-value-method' },
          { title: 'hideAddItemTemplate()', path: '/ionic-selectable/hide-add-item-template-method' },
          { title: 'hideLoading()', path: '/ionic-selectable/hide-loading-method' },
          { title: 'open()', path: '/ionic-selectable/open-method' },
          { title: 'search()', path: '/ionic-selectable/search-method' },
          { title: 'scrollToBottom()', path: '/ionic-selectable/scroll-to-bottom-method' },
          { title: 'scrollToTop()', path: '/ionic-selectable/scroll-to-top-method' },
          { title: 'showAddItemTemplate()', path: '/ionic-selectable/show-add-item-template-method' },
          { title: 'showLoading()', path: '/ionic-selectable/show-loading-method' },
          { title: 'startSearch()', path: '/ionic-selectable/start-search-method' },
          { title: 'toggleItems()', path: '/ionic-selectable/toggle-items-method' },
        ],
      },
      {
        title: 'Events',
        icon: 'mdi-lightning-bolt-outline',
        items: [
          { title: 'onAddItem', path: '/ionic-selectable/on-add-item-event' },
          { title: 'onDeleteItem', path: '/ionic-selectable/on-delete-item-event' },
          { title: 'onChange', path: '/ionic-selectable/on-change-event' },
          { title: 'onClear', path: '/ionic-selectable/on-clear-event' },
          { title: 'onClose', path: '/ionic-selectable/on-close-event' },
          { title: 'onInfiniteScroll', path: '/ionic-selectable/on-infinite-scroll-event' },
          { title: 'onOpen', path: '/ionic-selectable/on-open-event' },
          { title: 'onSaveItem', path: '/ionic-selectable/on-save-item-event' },
          { title: 'onSearch', path: '/ionic-selectable/on-search-event' },
          { title: 'onSearchFail', path: '/ionic-selectable/on-search-fail-event' },
          { title: 'onSearchSuccess', path: '/ionic-selectable/on-search-success-event' },
          { title: 'onSelect', path: '/ionic-selectable/on-select-event' },
        ],
      },
    ],
  },
};
