export const SIDE_MENU_GROUPS = [
  {
    title: 'Introduction',
    icon: 'mdi-script-text-outline',
    items: [
      { title: 'About', path: '/' },
      { title: 'Getting started', path: '/getting-started' },
      { title: 'Frequently asked questions', path: '/frequently-asked-questions' },
      { title: 'Errors', path: '/errors' },
      { title: 'Contributing', path: '/contributing' },
    ],
  },
  {
    title: 'Theming',
    icon: 'mdi-palette-outline',
    items: [{ title: 'CSS classes', path: '/css-classes' }],
  },
  {
    title: 'Use cases',
    icon: 'mdi-text-box-search-outline',
    items: [
      { title: 'Basic usage', path: '/basic-usage' },
      { title: 'Cascading selection', path: '/cascading-selection' },
      { title: 'Customizing footer buttons', path: '/customizing-footer-buttons' },
      { title: 'Disabling items', path: '/disabling-items' },
      { title: 'Firebase', path: '/firebase' },
      { title: 'Inside modal', path: '/inside-modal' },
      { title: 'Initial value', path: '/initial-value' },
      { title: 'Infinite scroll', path: '/infinite-scroll' },
      {
        title: 'Infinite scroll with multiple values',
        path: '/infinite-scroll-multiple-values',
      },
      { title: 'Ionic labels', path: '/ionic-labels' },
      { title: 'Primitive types', path: '/primitive-types' },
      { title: 'Search items asynchronously', path: '/search-items-asynchronously' },
      { title: 'Search by several item fields', path: '/search-by-several-item-fields' },
      { title: 'Virtual scroll', path: '/virtual-scroll' },
    ],
  },
  {
    title: 'Grouping',
    icon: 'mdi-file-tree',
    items: [
      { title: 'Grouping items', path: '/grouping-items' },
      {
        title: 'Grouping items with virtual scroll',
        path: '/grouping-items-virtual-scroll',
      },
    ],
  },
  {
    title: 'Editing',
    icon: 'mdi-square-edit-outline',
    items: [
      {
        title: 'Adding, editing and deleting items',
        path: '/editing-adding-editing-and-deleting-items',
      },
      {
        title: 'Adding, editing and deleting items asynchronously',
        path: '/editing-adding-editing-and-deleting-items-asynchronously',
      },
      {
        title: 'Adding item when search fails',
        path: '/editing-adding-item-when-search-fails',
      },
      {
        title: 'Adding item asynchronously when search fails',
        path: '/editing-adding-item-asynchronously-when-search-fails',
      },
    ],
  },
  {
    title: 'Templates',
    icon: 'mdi-xml',
    items: [
      { title: 'Add item template', path: '/add-item-template' },
      { title: 'Close button template', path: '/close-button-template' },
      { title: 'Footer template', path: '/footer-template' },
      { title: 'Group template', path: '/group-template' },
      { title: 'Group end template', path: '/group-end-template' },
      { title: 'Header template', path: '/header-template' },
      { title: 'Icon template', path: '/icon-template' },
      { title: 'Item template', path: '/item-template' },
      { title: 'Item end template', path: '/item-end-template' },
      { title: 'Item icon template', path: '/item-icon-template' },
      { title: 'Message template', path: '/message-template' },
      { title: 'Multiple values template', path: '/multiple-values-template' },
      {
        title: 'Multiple values with ellipsis template',
        path: '/multiple-values-ellipsis-template',
      },
      { title: 'Placeholder template', path: '/placeholder-template' },
      { title: 'Search fail template', path: '/search-fail-template' },
      { title: 'Title template', path: '/title-template' },
      { title: 'Value template', path: '/value-template' },
    ],
  },
  {
    title: 'Forms',
    icon: 'mdi-form-select',
    items: [
      { title: 'FormArray', path: '/form-array' },
      { title: 'FormControl', path: '/form-control' },
      { title: 'Min/max selection', path: '/min-max-selection' },
    ],
  },
  {
    title: 'Fields',
    icon: 'mdi-cube-outline',
    items: [
      { title: 'addButtonText', path: '/add-button-text-field' },
      { title: 'canAddItem', path: '/can-add-item-field' },
      { title: 'canClear', path: '/can-clear-field' },
      { title: 'canDeleteItem', path: '/can-delete-item-field' },
      { title: 'canSaveItem', path: '/can-save-item-field' },
      { title: 'canSearch', path: '/can-search-field' },
      { title: 'clearButtonText', path: '/clear-button-text-field' },
      { title: 'closeButtonText', path: '/close-button-text-field' },
      { title: 'closeButtonSlot', path: '/close-button-slot-field' },
      { title: 'confirmButtonText', path: '/confirm-button-text-field' },
      { title: 'disabledItems', path: '/disabled-items-field' },
      { title: 'groupColor', path: '/group-color-field' },
      { title: 'groupValueField', path: '/group-value-field-field' },
      { title: 'groupTextField', path: '/group-text-field-field' },
      { title: 'hasInfiniteScroll', path: '/has-infinite-scroll-field' },
      { title: 'hasConfirmButton', path: '/has-confirm-button-field' },
      { title: 'hasSearchText', path: '/has-search-text-field' },
      { title: 'hasVirtualScroll', path: '/has-virtual-scroll-field' },
      { title: 'headerColor', path: '/header-color-field' },
      { title: 'itemIconSlot', path: '/item-icon-slot-field' },
      { title: 'items', path: '/items-field' },
      { title: 'itemsToConfirm', path: '/items-to-confirm-field' },
      { title: 'isEnabled', path: '/is-enabled-field' },
      { title: 'isMultiple', path: '/is-multiple-field' },
      { title: 'isConfirmButtonEnabled', path: '/is-confirm-button-enabled-field' },
      { title: 'isOnSearchEnabled', path: '/is-on-search-enabled-field' },
      { title: 'isOpened', path: '/is-opened-field' },
      { title: 'isSearching', path: '/is-searching-field' },
      { title: 'itemValueField', path: '/item-value-field-field' },
      { title: 'itemTextField', path: '/item-text-field-field' },
      { title: 'label', path: '/label-field' },
      { title: 'modalCssClass', path: '/modal-css-class-field' },
      { title: 'modalEnterAnimation', path: '/modal-enter-animation-field' },
      { title: 'modalLeaveAnimation', path: '/modal-leave-animation-field' },
      { title: 'placeholder', path: '/placeholder-field' },
      { title: 'searchDebounce', path: '/search-debounce-field' },
      { title: 'searchFailText', path: '/search-fail-text-field' },
      { title: 'searchPlaceholder', path: '/search-placeholder-field' },
      { title: 'searchText', path: '/search-text-field' },
      { title: 'shouldBackdropClose', path: '/should-backdrop-close-field' },
      { title: 'shouldFocusSearchbar', path: '/should-focus-searchbar-field' },
      { title: 'shouldStoreItemValue', path: '/should-store-item-value-field' },
      {
        title: 'virtualScrollApproxItemHeight',
        path: '/virtual-scroll-approx-item-height-field',
      },
      { title: 'virtualScrollHeaderFn', path: '/virtual-scroll-header-fn-field' },
    ],
  },
  {
    title: 'Methods',
    icon: 'mdi-code-parentheses',
    items: [
      { title: 'addItem()', path: '/add-item-method' },
      { title: 'clear()', path: '/clear-method' },
      { title: 'close()', path: '/close-method' },
      { title: 'confirm()', path: '/confirm-method' },
      { title: 'deleteItem()', path: '/delete-item-method' },
      { title: 'disableInfiniteScroll()', path: '/disable-infinite-scroll-method' },
      { title: 'enableInfiniteScroll()', path: '/enable-infinite-scroll-method' },
      { title: 'endInfiniteScroll()', path: '/end-infinite-scroll-method' },
      { title: 'endSearch()', path: '/end-search-method' },
      { title: 'hasValue()', path: '/has-value-method' },
      { title: 'hideAddItemTemplate()', path: '/hide-add-item-template-method' },
      { title: 'hideLoading()', path: '/hide-loading-method' },
      { title: 'open()', path: '/open-method' },
      { title: 'search()', path: '/search-method' },
      { title: 'scrollToBottom()', path: '/scroll-to-bottom-method' },
      { title: 'scrollToTop()', path: '/scroll-to-top-method' },
      { title: 'showAddItemTemplate()', path: '/show-add-item-template-method' },
      { title: 'showLoading()', path: '/show-loading-method' },
      { title: 'startSearch()', path: '/start-search-method' },
      { title: 'toggleItems()', path: '/toggle-items-method' },
    ],
  },
  {
    title: 'Events',
    icon: 'mdi-lightning-bolt-outline',
    items: [
      { title: 'onAddItem', path: '/on-add-item-event' },
      { title: 'onDeleteItem', path: '/on-delete-item-event' },
      { title: 'onChange', path: '/on-change-event' },
      { title: 'onClear', path: '/on-clear-event' },
      { title: 'onClose', path: '/on-close-event' },
      { title: 'onInfiniteScroll', path: '/on-infinite-scroll-event' },
      { title: 'onOpen', path: '/on-open-event' },
      { title: 'onSaveItem', path: '/on-save-item-event' },
      { title: 'onSearch', path: '/on-search-event' },
      { title: 'onSearchFail', path: '/on-search-fail-event' },
      { title: 'onSearchSuccess', path: '/on-search-success-event' },
      { title: 'onSelect', path: '/on-select-event' },
    ],
  },
];
